"""通用校验问题的稳定机器可读 code。"""

REPOSITORY_INVALID_ROOT = "repository.invalid_root"
SKILL_ROOT_MISSING = "skill.root_missing"
SKILL_NONE_FOUND = "skill.none_found"
SKILL_INVALID_NAME = "skill.invalid_name"
SKILL_MISSING_ENTRY = "skill.missing_entry"
SKILL_MULTIPLE_ENTRIES = "skill.multiple_entries"
SKILL_EMPTY_MARKDOWN = "skill.empty_markdown"
SKILL_INVALID_OPTIONAL_DIRECTORY = "skill.invalid_optional_directory"
SKILL_TEXT_UNREADABLE = "skill.text_unreadable"

FRONTMATTER_MISSING = "frontmatter.missing"
FRONTMATTER_INVALID = "frontmatter.invalid"
FRONTMATTER_MISSING_FIELD = "frontmatter.missing_field"
FRONTMATTER_NAME_MISMATCH = "frontmatter.name_mismatch"

MARKDOWN_REFERENCE_ABSOLUTE = "markdown.reference_absolute"
MARKDOWN_REFERENCE_ESCAPE = "markdown.reference_escape"
MARKDOWN_REFERENCE_MISSING = "markdown.reference_missing"

PYTHON_SYNTAX_ERROR = "python.syntax_error"
PYTHON_EXTERNAL_DEPENDENCY = "python.external_dependency"
PYTHON_IMPORT_ESCAPE = "python.import_escape"

PATH_SYMLINK_ESCAPE = "path.symlink_escape"
PATH_UNIGNORED_CACHE = "path.unignored_cache"
PATH_DS_STORE = "path.ds_store"
PATH_TEMPORARY_FILE = "path.temporary_file"

SECURITY_PRIVATE_KEY = "security.private_key"
SECURITY_SK_KEY = "security.sk_key"
SECURITY_AWS_ACCESS_KEY = "security.aws_access_key"
SECURITY_BEARER_TOKEN = "security.bearer_token"
SECURITY_CREDENTIAL_ASSIGNMENT = "security.credential_assignment"

PLUGIN_IMPORT_FAILED = "plugin.import_failed"
PLUGIN_API_VERSION_UNSUPPORTED = "plugin.api_version_unsupported"
PLUGIN_INVALID_INTERFACE = "plugin.invalid_interface"
PLUGIN_NAME_MISMATCH = "plugin.name_mismatch"
PLUGIN_DUPLICATE = "plugin.duplicate"
PLUGIN_ORPHANED = "plugin.orphaned"
PLUGIN_EXECUTION_FAILED = "plugin.execution_failed"
PLUGIN_INVALID_RESULT = "plugin.invalid_result"
